### ISSUE TITLE
VMC in breeze mode makes the addons crash

### ISSUE THREAD

**Issue by alois-git** [jimmyd-be/Home-Assistant-Sensor-Renson-Ventilation#11]
First thanks for the work on this addon, it's really nice :)

I encountered a small but when turning the breeze mode on the VMC. The addon crash not being able to map the Breeze speed level.

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/renson/sensor.py", line 310, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/renson/fan.py", line 68, in _handle_coordinator_update
    self.current_speed = SPEED_MAPPING[level]
KeyError: 'Breeze'```

**Comment by alois-git** [comment]
Adding a type in the enum SPEED_MAPPING solve the issue (fan.py)

```
SPEED_MAPPING = {
    Level.OFF.value: 0,
    Level.HOLIDAY.value: 0,
    Level.LEVEL1.value: 1,
    Level.LEVEL2.value: 2,
    Level.LEVEL3.value: 3,
    Level.LEVEL4.value: 4,
    Level.BREEZE.value: 'Breeze',
}
```

See PR https://github.com/jimmyd-be/Home-Assistant-Sensor-Renson-Ventilation/pull/12

**Comment by jimmyd-be** [comment]
PR merged so this issue can be closed. Thanks for the PR.
