### ISSUE TITLE
Set Timer Level not working

### ISSUE THREAD

**Issue by donatti92** [jimmyd-be/Home-Assistant-Sensor-Renson-Ventilation#8]
Not sure if this is something general or just something in my setup.
Tried to use the renson.set-timer-level service, but home assistant is returing an issue with the following log
other services (set manual level for example) is working just fine.

Hope this helps!

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/renson/__init__.py:67
Integration: Renson
First occurred: 19:21:57 (2 occurrences)
Last logged: 19:22:07

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: can only concatenate str (not "Level") to str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/renson/__init__.py", line 67, in set_timer_level
    await hass.async_add_executor_job(renson_api.set_timer_level, level, time)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/renson_endura_delta/renson.py", line 139, in set_timer_level
    data = ValueData(str(time) + " min " + level)
TypeError: can only concatenate str (not "Level") to str
```

**Comment by tvanhove** [comment]
I have the same issue. Been trying to figure it out thinking it was something on my end configuration wise but seeing the exact same error coming through.

```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/renson/__init__.py:67
Integration: Renson
First occurred: 11:06:41 PM (1 occurrences)
Last logged: 11:06:41 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: can only concatenate str (not "Level") to str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/renson/__init__.py", line 67, in set_timer_level
    await hass.async_add_executor_job(renson_api.set_timer_level, level, time)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/renson_endura_delta/renson.py", line 139, in set_timer_level
    data = ValueData(str(time) + " min " + level)
TypeError: can only concatenate str (not "Level") to str
```

**Comment by jimmyd-be** [comment]
The issue should be fixed in the latest version. Please can you try again after updating?

**Comment by tvanhove** [comment]
Yes! Fixed the error and call went through perfect! Thanks for the quick fix
